{
 "title": "Blockchain Dashboard 1",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Blockchain Ledger Height",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 14, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ledger_blockchain_height{type=\"peer\"}",
     "legendFormat": "{{channel}}: {{instance}}"
    }
   ]
  },
  {
   "title": "Fabric Version",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "fabric_version{}", "legendFormat": "{{version}}" }
   ]
  },
  {
   "title": "Ledger Transaction Count",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 18, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "ledger_transaction_count{transaction_type=\"ENDORSER_TRANSACTION\", validation_code=\"VALID\"}",
     "legendFormat": "{{channel}}: {{instance}}"
    }
   ]
  },
  {
   "title": "Endorsement Proposals Received",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "endorser_proposals_received", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Endorser Proposal Success",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 9, "x": 9, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "endorser_successful_proposals", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "CouchDB Processing time",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "couchdb_processing_time_count" }
   ]
  },
  {
   "title": "Go Memstat GC CPU Fraction",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_memstats_gc_cpu_fraction{job!=\"prometheus\"}"
    }
   ]
  },
  {
   "title": "GRPC Server Stream Messages Received",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "grpc_server_stream_messages_received"
    }
   ]
  },
  {
   "title": "Ledger Transactions over time",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ledger_transaction_count{transaction_type=\"ENDORSER_TRANSACTION\", validation_code=\"VALID\"}",
     "legendFormat": "{{transaction_type}}"
    }
   ]
  },
  {
   "title": "Ledger Block Storage Commit Time",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ledger_blockstorage_commit_time_sum{}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Broadcast Processed Count (MyChannel)",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "broadcast_processed_count{}", "legendFormat": "{{channel}}" }
   ]
  }
 ]
}